repositoryUrl: https://github.com/BBong119/bbong119.github.io/blob/master

homePage: /

basicInfo: /dbr-basic-info/

userGuide: /dbr-basic-info/user-guide/
userGuide_windows: /dbr-basic-info/user-guide/windows/

evaluationTools: /dbr-basic-info/evaluation-tools/

detailedInfo: /dbr-detailed-info/

manual: /dbr-detailed-info/manual/
manual_interface: /dbr-detailed-info/manual/interface/
manual_interface_enum: /dbr-detailed-info/manual/interface/enumeration/
manual_interface_errorCode: /dbr-detailed-info/manual/interface/enumeration/error-code/
manual_interface_argument: /dbr-detailed-info/manual/interface/arguments/
manual_interface_c_and_cpp: /dbr-detailed-info/manual/interface/c-and-cpp/
manual_interface_struct: /dbr-detailed-info/manual/interface/c-and-cpp/struct/
manual_interface_c: /dbr-detailed-info/manual/interface/c-and-cpp/c/
manual_interface_cpp: /dbr-detailed-info/manual/interface/c-and-cpp/cpp/
manual_parameter: /dbr-detailed-info/manual/parameters/

demosSamples: /dbr-detailed-info/samples-and-demos/
demosSamples_appDemo: /dbr-detailed-info/samples-and-demos/

enhancements: /dbr-enhancements/

extendedInfo: /dbr-extended-info/

editIcon: /other-material/icon/editIcon.png
dynamsoft_logo: /other-material/logo/dynamsoft_logo.png
dbr_logo: /other-material/logo/dbr_logo.png

developing: /developing.html


kramdown:                                         
  syntax_highlighter: rouge  
